In [1]:
import numpy as np

In [2]:
arr=np.array([1,23,3])
arr

array([ 1, 23,  3])

In [3]:
arr1=np.array([[1,2,3],[4,5,6],[8,7,5]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [8, 7, 5]])

In [14]:
arr2=np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])