In [1]:
import numpy as np

In [3]:
# this is normalisation (0 aur 1 ke bech mein values aati hai usse normalisation kehte hai)
np.random.rand(4)  

array([0.68618999, 0.85300198, 0.96916728, 0.99574269])

In [4]:
# this is standardization (-3 aur 3 ke bech mein values aati hai usse standardization kehte hai)
np.random.randn(3)

array([-1.26547888,  1.70314737,  1.18065178])

In [9]:
# this generates an interger between 0 and 6
np.random.randint(6)

5

In [10]:
# this generates an interger between 10 and 32
np.random.randint(10,32)

18

In [12]:
# this generates any 5 integers between 10 and 30
np.random.randint(10,20,10)

array([11, 15, 15, 16, 14, 13, 19, 11, 10, 13], dtype=int32)