In [4]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr.shape

(3, 3)

In [7]:
arr.size

9

In [8]:
arr.dtype

dtype('int64')

In [9]:
# ARRAY METHODS

In [12]:
arr.min()

np.int64(1)

In [13]:
arr.max()

np.int64(9)

In [14]:
arr.sum()

np.int64(45)

In [15]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [16]:
arr.mean()

np.float64(5.0)

In [17]:
arr.argmax()

np.int64(8)

In [18]:
arr.argmin()

np.int64(0)

In [19]:
# reshaping & resizing

In [22]:
arr1= np.arange(1,31)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [25]:
arr2=arr1.reshape(6,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])