In [6]:
import numpy as np

In [7]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[5]

np.int64(16)

In [9]:
arr_slice=arr[9:2:-1]
arr_slice

array([20, 19, 18, 17, 16, 15, 14])

In [10]:
arr1=np.arange(1,31).reshape(6,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr1[3,2]

np.int64(18)

In [14]:
arr1[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
arr1[1]

array([ 6,  7,  8,  9, 10])

In [16]:
arr1[:,1]

array([ 2,  7, 12, 17, 22, 27])